# Generated by Django 3.0.5 on 2020-04-13 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20200413_1049'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('where', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=300)),
                ('languages', models.CharField(max_length=300)),
                ('summary', models.CharField(max_length=1000)),
            ],
        ),
    ]
