# Generated by Django 3.0.5 on 2020-04-13 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_auto_20200413_1250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='summary',
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
